pub mod buffer;
pub mod color;
pub mod config;
pub mod geometry;
pub mod keyboard;
pub mod margin;
pub mod menu;
pub mod message;
pub mod pointer;
pub mod socket;
pub mod texture;

pub use buffer::BufferMetadata;
pub use color::rgba::RgbaColor;
pub use config::DebugOverlayConfig;
#[cfg(feature = "serde")]
pub use config::CompositorConfig;
#[cfg(feature = "serde")]
pub use config::Config;
#[cfg(feature = "serde")]
pub use config::ConfigError;
#[cfg(feature = "serde")]
pub use config::WindowConfig;
pub use geometry::position::Position;
pub use geometry::rectangle::Rectangle;
pub use geometry::size::Size;
pub use keyboard::KeyboardLayout;
pub use margin::Margins;
pub use menu::MenuItem;
pub use message::CompositorMessage;
pub use pointer::PointerPosition;
pub use socket::Socket;
pub use texture::BGRA;
pub use texture::PixelData;
pub use texture::RGBA;
